export type TemplateTask = {
  phase: string;
  name: string;
  offset: number;   // days from project start
  duration: number; // days
  milestone: boolean;
  trade?: string;
};

export type ScheduleTemplate = {
  key: string;
  label: string;
  tasks: TemplateTask[];
};

// ─── Bathroom Remodel ─────────────────────────────────────────────────────────
const BATHROOM_TASKS: TemplateTask[] = [
  { phase: "1 - Demo",          name: "Demolition & debris removal",     offset: 0,   duration: 2, milestone: false, trade: "Demo" },
  { phase: "2 - Rough-In",      name: "Plumbing rough-in",               offset: 2,   duration: 2, milestone: false, trade: "Plumbing" },
  { phase: "2 - Rough-In",      name: "Electrical rough-in",             offset: 2,   duration: 1, milestone: false, trade: "Electrical" },
  { phase: "2 - Rough-In",      name: "HVAC / exhaust fan rough-in",     offset: 3,   duration: 1, milestone: false, trade: "HVAC" },
  { phase: "2 - Rough-In",      name: "Rough-in inspection",             offset: 4,   duration: 1, milestone: true },
  { phase: "3 - Waterproofing", name: "Backer board installation",       offset: 5,   duration: 1, milestone: false, trade: "Tile" },
  { phase: "3 - Waterproofing", name: "Waterproofing membrane",          offset: 6,   duration: 1, milestone: false, trade: "Tile" },
  { phase: "4 - Tile",          name: "Floor tile installation",         offset: 7,   duration: 2, milestone: false, trade: "Tile" },
  { phase: "4 - Tile",          name: "Wall & shower tile installation", offset: 9,   duration: 3, milestone: false, trade: "Tile" },
  { phase: "4 - Tile",          name: "Grout & seal",                   offset: 12,  duration: 1, milestone: false, trade: "Tile" },
  { phase: "5 - Fixtures",      name: "Vanity & plumbing fixtures",      offset: 13,  duration: 2, milestone: false, trade: "Plumbing" },
  { phase: "5 - Fixtures",      name: "Electrical fixtures & lighting",  offset: 13,  duration: 1, milestone: false, trade: "Electrical" },
  { phase: "5 - Fixtures",      name: "Shower door / enclosure",        offset: 15,  duration: 1, milestone: false, trade: "Glass" },
  { phase: "6 - Finishes",      name: "Paint & trim",                   offset: 16,  duration: 1, milestone: false, trade: "Paint" },
  { phase: "6 - Finishes",      name: "Final inspection & punch list",  offset: 17,  duration: 1, milestone: true },
];

// ─── Addition (Allison's Addition) ───────────────────────────────────────────
const ADDITION_TASKS: TemplateTask[] = [
  { phase: "Shell",          name: "Demolition existing wood structure", offset: 0,   duration: 3,  milestone: false, trade: "Demo" },
  { phase: "Shell",          name: "Excavation",                         offset: 3,   duration: 3,  milestone: false, trade: "Excavation" },
  { phase: "Shell",          name: "Forming",                            offset: 91,  duration: 1,  milestone: false, trade: "Concrete" },
  { phase: "Shell",          name: "Footings Rebars Installation",       offset: 92,  duration: 3,  milestone: false, trade: "Concrete" },
  { phase: "Shell",          name: "Footings Inspection",                offset: 95,  duration: 1,  milestone: false },
  { phase: "Shell",          name: "Footings Pouring Concrete",          offset: 98,  duration: 1,  milestone: false, trade: "Concrete" },
  { phase: "Shell",          name: "1st Lift Columns",                   offset: 100, duration: 4,  milestone: false, trade: "Masonry" },
  { phase: "Shell",          name: "1st Lift Blocks",                    offset: 100, duration: 4,  milestone: false, trade: "Masonry" },
  { phase: "Shell",          name: "Tie Beam Rebars Installation",       offset: 106, duration: 5,  milestone: false, trade: "Concrete" },
  { phase: "Shell",          name: "Tie Beam Rebars Inspection",         offset: 113, duration: 1,  milestone: false },
  { phase: "Shell",          name: "Tie Beam Pouring Concrete",          offset: 114, duration: 1,  milestone: false, trade: "Concrete" },
  { phase: "Shell",          name: "SOG Rebars Installation",            offset: 113, duration: 4,  milestone: false, trade: "Concrete" },
  { phase: "Shell",          name: "SOG Inspection",                     offset: 119, duration: 1,  milestone: true },
  { phase: "Shell",          name: "SOG Pouring Concrete",               offset: 120, duration: 1,  milestone: false, trade: "Concrete" },
  { phase: "Shell",          name: "Trusses installation",               offset: 114, duration: 10, milestone: false, trade: "Framing" },
  { phase: "Shell",          name: "Plywood Sheathing",                  offset: 128, duration: 5,  milestone: false, trade: "Framing" },
  { phase: "Plumbing",       name: "Plumbing Rough Installation",        offset: 8,   duration: 1,  milestone: false, trade: "Plumbing" },
  { phase: "Plumbing",       name: "Plumbing Rough Inspection",          offset: 9,   duration: 1,  milestone: true },
  { phase: "Plumbing",       name: "Plumbing Underground Installation",  offset: 106, duration: 4,  milestone: false, trade: "Plumbing" },
  { phase: "Plumbing",       name: "Plumbing Underground Inspection",    offset: 112, duration: 1,  milestone: true },
  { phase: "Plumbing",       name: "Bathtub Installation",               offset: 151, duration: 1,  milestone: false, trade: "Plumbing" },
  { phase: "Plumbing",       name: "Vanity Installation",                offset: 204, duration: 1,  milestone: false, trade: "Plumbing" },
  { phase: "Plumbing",       name: "Toilets Installation",               offset: 213, duration: 1,  milestone: false, trade: "Plumbing" },
  { phase: "Plumbing",       name: "Plumbing Final Inspection",          offset: 218, duration: 1,  milestone: true },
  { phase: "Electrical",     name: "Electrical Underground",             offset: 95,  duration: 1,  milestone: false, trade: "Electrical" },
  { phase: "Electrical",     name: "Electrical Rough",                   offset: 151, duration: 5,  milestone: false, trade: "Electrical" },
  { phase: "Electrical",     name: "Electrical Rough Inspection",        offset: 158, duration: 1,  milestone: true },
  { phase: "Electrical",     name: "Electrical Trims and outlets",       offset: 204, duration: 4,  milestone: false, trade: "Electrical" },
  { phase: "Electrical",     name: "Electrical Final Inspection",        offset: 210, duration: 1,  milestone: true },
  { phase: "Roof",           name: "Flat Roof Installation",             offset: 135, duration: 5,  milestone: false, trade: "Roofing" },
  { phase: "Roof",           name: "Flat Roof Final Inspection",         offset: 142, duration: 1,  milestone: true },
  { phase: "Windows",        name: "Windows Installation",               offset: 143, duration: 3,  milestone: false },
  { phase: "Windows",        name: "Windows Inspection",                 offset: 148, duration: 1,  milestone: true },
  { phase: "Drywall",        name: "Framing Installation",               offset: 143, duration: 5,  milestone: false, trade: "Framing" },
  { phase: "Drywall",        name: "Framing Inspection",                 offset: 150, duration: 1,  milestone: true },
  { phase: "Drywall",        name: "Wall Insulation",                    offset: 151, duration: 3,  milestone: false },
  { phase: "Drywall",        name: "Roof Insulation",                    offset: 156, duration: 4,  milestone: false },
  { phase: "Drywall",        name: "Insulation Inspection",              offset: 162, duration: 1,  milestone: true },
  { phase: "Drywall",        name: "Drywall Hanging",                    offset: 163, duration: 10, milestone: false, trade: "Drywall" },
  { phase: "Drywall",        name: "Drywall Inspection",                 offset: 177, duration: 1,  milestone: true },
  { phase: "Drywall",        name: "Drywall Finish",                     offset: 178, duration: 7,  milestone: false, trade: "Drywall" },
  { phase: "Drywall",        name: "Drywall Finishes Touch Ups",         offset: 189, duration: 1,  milestone: false, trade: "Drywall" },
  { phase: "HVAC",           name: "HVAC Ducts Installation",            offset: 151, duration: 3,  milestone: false, trade: "HVAC" },
  { phase: "HVAC",           name: "HVAC Rough Inspection",              offset: 156, duration: 1,  milestone: true },
  { phase: "HVAC",           name: "HVAC Mini Split Installation",       offset: 204, duration: 1,  milestone: false, trade: "HVAC" },
  { phase: "HVAC",           name: "HVAC Final Inspection",              offset: 212, duration: 1,  milestone: true },
  { phase: "Interior Paint", name: "Ceilings Paint",                     offset: 190, duration: 3,  milestone: false, trade: "Paint" },
  { phase: "Interior Paint", name: "Wall Paint",                         offset: 193, duration: 7,  milestone: false, trade: "Paint" },
  { phase: "Tiles",          name: "Bathroom Wall Tiles",                offset: 178, duration: 5,  milestone: false, trade: "Tile" },
  { phase: "Tiles",          name: "Flooring Tiles",                     offset: 204, duration: 7,  milestone: false, trade: "Tile" },
  { phase: "Fine Carpentry", name: "Doors Installation",                 offset: 213, duration: 3,  milestone: false, trade: "Carpentry" },
  { phase: "Fine Carpentry", name: "Doors Casings Installation",         offset: 218, duration: 5,  milestone: false, trade: "Carpentry" },
  { phase: "Fine Carpentry", name: "Baseboards Installation",            offset: 218, duration: 10, milestone: false, trade: "Carpentry" },
  { phase: "Exterior",       name: "Stucco",                             offset: 151, duration: 60, milestone: false },
  { phase: "Exterior",       name: "Exterior Paint",                     offset: 151, duration: 60, milestone: false, trade: "Paint" },
  { phase: "Closeout",       name: "Final Cleaning",                     offset: 234, duration: 1,  milestone: false },
  { phase: "Closeout",       name: "Building Final Inspection",          offset: 234, duration: 1,  milestone: true },
];

// ─── Custom Home (Camden / 97 Camden) ────────────────────────────────────────
const CUSTOM_HOME_TASKS: TemplateTask[] = [
  { phase: "Landscaping Prep",       name: "Root Protection",                        offset: 0,   duration: 5,   milestone: false },
  { phase: "Landscaping Prep",       name: "Tree Removal",                           offset: 1,   duration: 3,   milestone: false },
  { phase: "Temp for construction",  name: "Dig Trench to install pipes underground", offset: 49,  duration: 3,   milestone: false },
  { phase: "Temp for construction",  name: "Install Temp for construction",           offset: 50,  duration: 5,   milestone: false },
  { phase: "Temp for construction",  name: "Temp for construction Permit Inspection", offset: 57,  duration: 1,   milestone: true },
  { phase: "Temp for construction",  name: "FPL install",                             offset: 58,  duration: 10,  milestone: false },
  { phase: "Grade Beams",            name: "Excavation",                              offset: 25,  duration: 5,   milestone: false, trade: "Excavation" },
  { phase: "Grade Beams",            name: "Set Batter boards and gridlines",         offset: 25,  duration: 3,   milestone: false },
  { phase: "Grade Beams",            name: "Set Forms",                               offset: 25,  duration: 3,   milestone: false, trade: "Concrete" },
  { phase: "Grade Beams",            name: "Rebars Installation",                     offset: 25,  duration: 12,  milestone: false, trade: "Concrete" },
  { phase: "Grade Beams",            name: "Grade Beam Inspection",                   offset: 37,  duration: 1,   milestone: true },
  { phase: "Grade Beams",            name: "Pour Grade Beam",                         offset: 78,  duration: 2,   milestone: false, trade: "Concrete" },
  { phase: "Grade Beams",            name: "Forms Removal",                           offset: 80,  duration: 3,   milestone: false },
  { phase: "Plumbing-Underground",   name: "Tie to Main Sewer",                       offset: 56,  duration: 5,   milestone: false, trade: "Plumbing" },
  { phase: "Plumbing-Underground",   name: "Map out all 1st floor sewer connections", offset: 63,  duration: 5,   milestone: false, trade: "Plumbing" },
  { phase: "Plumbing-Underground",   name: "Install 4 Hosebibs",                      offset: 56,  duration: 2,   milestone: false, trade: "Plumbing" },
  { phase: "Plumbing-Underground",   name: "Underground sewer lines",                 offset: 98,  duration: 20,  milestone: false, trade: "Plumbing" },
  { phase: "Plumbing-Underground",   name: "Water Service",                           offset: 98,  duration: 8,   milestone: false, trade: "Plumbing" },
  { phase: "Plumbing-Underground",   name: "Plumbing Underground Inspection",         offset: 126, duration: 1,   milestone: true },
  { phase: "Stem Wall & Columns",    name: "Backfill for blocks",                     offset: 80,  duration: 3,   milestone: false },
  { phase: "Stem Wall & Columns",    name: "Blocks Install",                          offset: 80,  duration: 3,   milestone: false, trade: "Masonry" },
  { phase: "Stem Wall & Columns",    name: "Fill cells installation",                 offset: 93,  duration: 3,   milestone: false, trade: "Masonry" },
  { phase: "Stem Wall & Columns",    name: "Pouring concrete fill cells and columns", offset: 95,  duration: 2,   milestone: false, trade: "Concrete" },
  { phase: "Slab On Grade",          name: "2nd backfill at 9' ngvd",                 offset: 127, duration: 6,   milestone: false },
  { phase: "Slab On Grade",          name: "Compaction",                              offset: 135, duration: 1,   milestone: false },
  { phase: "Slab On Grade",          name: "Termite Treatment",                       offset: 136, duration: 1,   milestone: false },
  { phase: "Slab On Grade",          name: "Vapor barrier installation",              offset: 137, duration: 1,   milestone: false },
  { phase: "Slab On Grade",          name: "Rebars installation",                     offset: 140, duration: 11,  milestone: false, trade: "Concrete" },
  { phase: "Slab On Grade",          name: "Rebars and metal inspection",             offset: 156, duration: 1,   milestone: true },
  { phase: "Slab On Grade",          name: "Pouring concrete on SOG",                offset: 157, duration: 1,   milestone: false, trade: "Concrete" },
  { phase: "1st Lift CMU Wall",      name: "1st Lift CMU Wall & Columns",             offset: 161, duration: 20,  milestone: false, trade: "Masonry" },
  { phase: "2nd Floor Slab",         name: "2nd Floor Slab & beams & Tie Beams",      offset: 190, duration: 29,  milestone: false, trade: "Concrete" },
  { phase: "2nd Lift CMU Wall",      name: "2nd Lift CMU Wall & Columns",             offset: 232, duration: 22,  milestone: false, trade: "Masonry" },
  { phase: "Roof Structure",         name: "Wood Trusses & Plywood Sheathing",        offset: 263, duration: 10,  milestone: false, trade: "Framing" },
  { phase: "Roof Structure",         name: "30# felt installation",                   offset: 275, duration: 10,  milestone: false, trade: "Roofing" },
  { phase: "Roof Structure",         name: "Peel and Stick",                          offset: 289, duration: 15,  milestone: false, trade: "Roofing" },
  { phase: "Roof Structure",         name: "Roofing Tiles Installation",              offset: 487, duration: 100, milestone: false, trade: "Roofing" },
  { phase: "Roof Structure",         name: "Gutters and Downspouts",                  offset: 820, duration: 10,  milestone: false, trade: "Roofing" },
  { phase: "Roof Structure",         name: "Roof Final inspection",                   offset: 772, duration: 1,   milestone: true },
  { phase: "Framing",                name: "Framing Installation",                    offset: 277, duration: 198, milestone: false, trade: "Framing" },
  { phase: "Framing",                name: "Framing Inspection",                      offset: 576, duration: 1,   milestone: true },
  { phase: "HVAC Underground",       name: "HVAC Underground work",                   offset: 164, duration: 1,   milestone: false, trade: "HVAC" },
  { phase: "HVAC Underground",       name: "HVAC Underground inspection",             offset: 165, duration: 1,   milestone: true },
  { phase: "Plumbing Rough",         name: "Plumbing Rough Copper lines",             offset: 289, duration: 90,  milestone: false, trade: "Plumbing" },
  { phase: "Plumbing Rough",         name: "Shower pan installation",                 offset: 575, duration: 10,  milestone: false, trade: "Plumbing" },
  { phase: "Plumbing Rough",         name: "Plumbing Rough Inspection",               offset: 589, duration: 1,   milestone: true },
  { phase: "Temp for construction",  name: "Sleeves Installation",                    offset: 141, duration: 1,   milestone: false },
  { phase: "Temp for construction",  name: "Electrical Underground Inspection",       offset: 142, duration: 1,   milestone: true },
  { phase: "Electrical-Rough",       name: "Rough Wiring",                            offset: 379, duration: 30,  milestone: false, trade: "Electrical" },
  { phase: "Electrical-Rough",       name: "Rough Electrical",                        offset: 513, duration: 62,  milestone: false, trade: "Electrical" },
  { phase: "Electrical-Rough",       name: "Prewiring & electrical panel installation",offset: 563, duration: 30, milestone: false, trade: "Electrical" },
  { phase: "Electrical-Rough",       name: "Housing installation",                    offset: 577, duration: 15,  milestone: false, trade: "Electrical" },
  { phase: "Electrical-Rough",       name: "Rough Electrical Inspection",             offset: 598, duration: 1,   milestone: true },
  { phase: "Windows",                name: "Wood bucking installation",               offset: 457, duration: 30,  milestone: false },
  { phase: "Windows",                name: "Waterproofing wood bucking",              offset: 457, duration: 25,  milestone: false },
  { phase: "Windows",                name: "1st Floor Windows Installation",          offset: 686, duration: 80,  milestone: false },
  { phase: "Windows",                name: "2nd Floor Windows Installation",          offset: 686, duration: 80,  milestone: false },
  { phase: "Windows",                name: "2nd Floor Doors Installation",            offset: 686, duration: 30,  milestone: false },
  { phase: "Wall Insulation",        name: "Wall Insulation",                         offset: 569, duration: 20,  milestone: false },
  { phase: "Drywall Hanging",        name: "Drywall Hanging",                         offset: 597, duration: 60,  milestone: false, trade: "Drywall" },
  { phase: "Drywall Hanging",        name: "Drywall Inspection",                      offset: 681, duration: 1,   milestone: true },
  { phase: "Drywall Finish",         name: "Drywall Finish Main parts",               offset: 735, duration: 10,  milestone: false, trade: "Drywall" },
  { phase: "Drywall Finish",         name: "Drywall Finishes Touch Ups",              offset: 735, duration: 25,  milestone: false, trade: "Drywall" },
  { phase: "HVAC Rough",             name: "HVAC Ducts Installation",                 offset: 504, duration: 60,  milestone: false, trade: "HVAC" },
  { phase: "HVAC Rough",             name: "HVAC Rough Inspection",                   offset: 546, duration: 1,   milestone: true },
  { phase: "HVAC Rough",             name: "Blades installation",                     offset: 760, duration: 10,  milestone: false, trade: "HVAC" },
  { phase: "HVAC Final",             name: "Installation of 5 AC condensers",         offset: 795, duration: 10,  milestone: false, trade: "HVAC" },
  { phase: "HVAC Final",             name: "Installation of thermostats",             offset: 792, duration: 1,   milestone: false, trade: "HVAC" },
  { phase: "HVAC Final",             name: "HVAC final inspection",                   offset: 855, duration: 1,   milestone: true },
  { phase: "Staircase",              name: "Installation of rough staircase",         offset: 547, duration: 7,   milestone: false, trade: "Carpentry" },
  { phase: "Staircase",              name: "Handrail Fabrication",                    offset: 793, duration: 40,  milestone: false },
  { phase: "Staircase",              name: "Handrail Installation",                   offset: 849, duration: 10,  milestone: false, trade: "Carpentry" },
  { phase: "All Bathrooms Tiles",    name: "All Bathrooms Tiles Installation",         offset: 687, duration: 50,  milestone: false, trade: "Tile" },
  { phase: "Flooring",               name: "Subflooring 2nd Floor",                   offset: 658, duration: 15,  milestone: false },
  { phase: "Flooring",               name: "Wood floor installation",                 offset: 812, duration: 10,  milestone: false, trade: "Carpentry" },
  { phase: "Flooring",               name: "Flat Work Stone Installation",            offset: 717, duration: 20,  milestone: false },
  { phase: "Cabinetry",              name: "Kitchen Cabinetry Installation",          offset: 827, duration: 10,  milestone: false },
  { phase: "Cabinetry",              name: "Vanities Installation",                   offset: 788, duration: 6,   milestone: false },
  { phase: "Cabinetry",              name: "Closets Installation",                    offset: 822, duration: 4,   milestone: false },
  { phase: "Cabinetry",              name: "Butler's Pantry Installation",            offset: 840, duration: 3,   milestone: false },
  { phase: "Interior Doors",         name: "Interior Doors Delivery",                 offset: 793, duration: 1,   milestone: false },
  { phase: "Interior Doors",         name: "Interior Doors Installation",             offset: 794, duration: 25,  milestone: false, trade: "Carpentry" },
  { phase: "Interior Doors",         name: "Interior Doors Painting",                 offset: 829, duration: 10,  milestone: false, trade: "Paint" },
  { phase: "Trim and Moldings",      name: "Baseboard Installation",                  offset: 844, duration: 15,  milestone: false, trade: "Carpentry" },
  { phase: "Trim and Moldings",      name: "Crown molding installation",              offset: 844, duration: 18,  milestone: false, trade: "Carpentry" },
  { phase: "Interior Painting",      name: "Primer all ceilings",                     offset: 675, duration: 5,   milestone: false, trade: "Paint" },
  { phase: "Interior Painting",      name: "Paint all ceilings",                      offset: 756, duration: 4,   milestone: false, trade: "Paint" },
  { phase: "Interior Painting",      name: "Interior Wall Paint",                     offset: 799, duration: 15,  milestone: false, trade: "Paint" },
  { phase: "Interior Painting",      name: "Baseboards and Crown Moldings Paint",     offset: 870, duration: 10,  milestone: false, trade: "Paint" },
  { phase: "Plumbing Trim",          name: "Shower/Bathtub Trim installation",        offset: 757, duration: 1,   milestone: false, trade: "Plumbing" },
  { phase: "Plumbing Trim",          name: "Vanity Faucets Installation",             offset: 798, duration: 10,  milestone: false, trade: "Plumbing" },
  { phase: "Plumbing Trim",          name: "Toilets Installation",                    offset: 892, duration: 10,  milestone: false, trade: "Plumbing" },
  { phase: "Plumbing Trim",          name: "Final Plumbing inspection",               offset: 906, duration: 1,   milestone: true },
  { phase: "Electrical Final",       name: "Outlets Installation",                    offset: 813, duration: 15,  milestone: false, trade: "Electrical" },
  { phase: "Electrical Final",       name: "Special order Lights Installation",       offset: 812, duration: 25,  milestone: false, trade: "Electrical" },
  { phase: "Electrical Final",       name: "Electrical final inspection",             offset: 933, duration: 1,   milestone: true },
  { phase: "Stucco & Exterior",      name: "Apply BASF 581 waterproofing",            offset: 756, duration: 20,  milestone: false },
  { phase: "Stucco & Exterior",      name: "Stucco rest of the house",                offset: 828, duration: 30,  milestone: false },
  { phase: "Stucco & Exterior",      name: "Exterior Paint",                          offset: 884, duration: 15,  milestone: false, trade: "Paint" },
  { phase: "Stucco & Exterior",      name: "Exterior Trim Installation",              offset: 827, duration: 20,  milestone: false },
  { phase: "Landscaping",            name: "Irrigation",                              offset: 826, duration: 17,  milestone: false },
  { phase: "Landscaping",            name: "Landscaping",                             offset: 840, duration: 7,   milestone: false },
  { phase: "Pool",                   name: "Pool and Mikvah Construction",            offset: 820, duration: 30,  milestone: false },
  { phase: "Closeout",               name: "Final Cleaning",                          offset: 955, duration: 3,   milestone: false },
];

export const SCHEDULE_TEMPLATES: ScheduleTemplate[] = [
  { key: "bathroom",    label: "🛁 Bathroom Remodel",  tasks: BATHROOM_TASKS },
  { key: "addition",   label: "🏠 Addition",            tasks: ADDITION_TASKS },
  { key: "custom-home", label: "🏛️ Custom Home",        tasks: CUSTOM_HOME_TASKS },
];
