ALTER TABLE "ChangeOrder" ADD COLUMN IF NOT EXISTS "timeDelay" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "ChangeOrder" ADD COLUMN IF NOT EXISTS "daysDelayed" INTEGER;
ALTER TABLE "ChangeOrder" ADD COLUMN IF NOT EXISTS "billingStatus" TEXT;
ALTER TABLE "ChangeOrder" ADD COLUMN IF NOT EXISTS "approverIp" TEXT;
